my:
        greeting: Hello world from config server
        list: 
           value: One, Two, Three, Four


db:
        connection: connection-string-here-from config server
        host: 127.0.0.1
        port: 1200
 
