status:
        desc: room-service cloud config connected.....
        
spring:
  profiles:
    active: local

db:
        database:
                url: jdbc:mysql://localhost:3306/pace_labs
                username: root
                password: shan@1234
                driverclass: com.mysql.jdbc.Driver
        jpa:
          hibernate:
                  ddl-auto: none
          show-sql: true        

