db:
        desc: connecting to mysql db
        
spring:
  profiles:
    active: local

Spring:
        datasource:
                url: jdbc:mysql://localhost:3306/pace_labs
                username: root
                password: shan@1234
                driver-class-name: com.mysql.jdbc.Driver
        jpa:
          hibernate:
                  ddl-auto: none
          show-sql: true        

